version: 1.0
component: deployment
env:

files:
  # This section is to define how the files in the artifact shall 
  # be put on the compute instance
  - source: /
    destination: /tmp
steps:
  # This section is to define the scripts that each step shall run on the instance after file copy.
  - stepType: Command
    name: Setup and Deploy
    command: |
      mkdir -p /tmp/kube
      cd  /tmp/kube
      python3 -m pip install --user oci-cli
      export OCI_CLI_AUTH=instance_principal
      export PATH=$PATH:~/.local/bin/
      oci artifacts generic artifact download-by-path --repository-id ${KUBE_ARTIFACT_ID} --artifact-path kube_artifacts --artifact-version ${BUILDRUN_HASH} --file kube_manifest.yaml
      echo "Running with cluster ID ${OKE_OCID} Region ${OCI_REGION} Endpoint ${OKE_ENDPOINT}"
      oci ce cluster create-kubeconfig --cluster-id ${OKE_OCID} --file kconfig --region ${OCI_REGION} --token-version 2.0.0  --kube-endpoint ${OKE_ENDPOINT}
      export KUBECONFIG="kconfig"
      kubectl get nodes
      cat kube_manifest.yaml |envsubst|kubectl apply -f -
      kubectl get all 
    
    timeoutInSeconds: 600

 