version: 1.0
component: deployment
env:

files:
  # This section is to define how the files in the artifact shall 
  # be put on the compute instance
  - source: /
    destination: /tmp
steps:
  # This section is to define the scripts that each step shall run on the instance after file copy.
  - stepType: Command
    name: Reading from Local artifact
    command: |
      mkdir -p /tmp/kube
      cd  /tmp/kube
      python3 -m pip install --user oci-cli
      export OCI_CLI_AUTH=instance_principal
      export PATH=$PATH:~/.local/bin/
# Incase of kubectl not installed previoously ,use one of the option (according to the os) and add here - https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/
      oci artifacts generic artifact download-by-path --repository-id ${KUBE_ARTIFACT_ID} --artifact-path kube_artifacts --artifact-version ${BUILDRUN_HASH} --file ./kube_manifest.yaml
      oci ce cluster create-kubeconfig --cluster-id ${OKE_OCID} --file kconfig --region ${OCI_REGION} --token-version 2.0.0  --kube-endpoint ${OKE_ENDPOINT}
      export KUBECONFIG="kconfig"
      kubectl get nodes
      kubectl apply -f kube_manifest.yaml
      kubectl get all 

    timeoutInSeconds: 600